- app/assets/stylesheets/application.scss
- app/data.js
- app/routes.js
- app/views/back-online.html
- app/views/synced-error-try-again.html
- app/views/synced-error.html
- app/views/synced-ok.html
A follow-on from:
https://childhood-vaccinations.designhistory.app/manual-offline-syncing
- Page to enable manual sync
- A syncing and success page
- An error page if there was a conflict
- An error page if the site is down (but the user is online)
https://user-images.githubusercontent.com/319055/228227269-0856efaa-0454-4091-927a-56c29f5ceddf.mov
> Create a journey for explicitly syncing offline changes

- app/assets/stylesheets/application.scss
- app/data.js
- app/generators/campaign.js
- app/generators/vaccination-record.js
- app/generators/vaccines.js
- app/routes.js
- app/routes/vaccination.js
- app/routes/vaccine-batches.js
- app/views/campaign/_children-banner.html
- app/views/campaign/child/_vaccination-recorded.html
- app/views/campaign/index.html
- app/views/dashboard.html
- app/views/vaccination/_single-vaccine-details.html
- app/views/vaccination/which-batch.html
- app/views/vaccines.html
- app/views/vaccines/batch.html
- app/wizards/vaccination.js
https://childhood-vaccinations.designhistory.app/managing-vaccine-batches
- Manage vaccines from the dashboard, rather than per school session
- Ask which batch is being used when vaccinating
- Allow users to pick a default batch for the day (we will not ask for the batch again that day)
- Add links for adding, archiving and changing batches – designs not implemented
Some data cleanups:
- a vaccination record now contains a batch number which is used as a reference to the vaccine details
- no vaccines are kept against the campaign any more
> Batch redesign

- app/enums.js
- app/generators/child.js
- app/generators/consent.js
- app/generators/parent.js
- app/generators/triage-needed.js
- app/globals.js
- app/routes/consent.js
- app/views/campaign/child/_consent-triage.html
- app/views/consent/confirm.html
- app/views/consent/why-not-consenting.html
- app/wizards/consent.js
- Allow capturing of consent from the child page on triage
- The journey ends after confirmation
- Users are currently returned to the child page, this might need to be the children list/tab
- If there is no response, this is essentially a no-op
- Refusals go into "Do not vaccinate" not "Check refusal"
- Permission given goes into "Vaccinate" in the "No triage needed" tab
- This design does not support more complex cases where a follow up triage might be needed
https://github.com/nhsuk/record-childrens-vaccinations-prototype/assets/319055/93ba27c4-8d21-432e-9b10-571fa4c88df3
> Allow users to get consent during triage

- app/enums.js
- app/routes/consent.js
- app/views/campaign/child-triage.html
- app/views/campaign/child/_details.html
- app/views/campaign/child/_triage-fields.html
- app/views/consent/confirm.html
- app/views/consent/health-questions.html
https://github.com/nhsuk/record-childrens-vaccinations-prototype/assets/319055/5e46f966-9292-400c-afa8-d4c5ef564a15
- Add triage status to health questions page
- Show triage notes and status on confirm page
- Set triage status action needed and triage statuses based on response
Covers the scenarios:
- Consent given, but health questions mean "do not vaccinate" or "keep in triage"
During the record flow we still ask "was the vaccine given" and capture a reason why not. This is MVP and we might need to refine this journey, maybe shortcutting those last questions altogether.
> Allow setting triage status (and notes) when getting consent

- app/views/campaign/child/_consent-triage.html
This would allow SAIS nurses to document failed attempts to get verbal consent.
> Allow triage notes even when consent hasn't been provided

- package-lock.json
- package.json
4.0.0 is missing a changelog entry.
> Downgrade to rollup-plugin-scss 3.0.0

- app/generators/child.js
- app/generators/consent.js
- app/generators/triage-needed.js
- app/routes/consent.js
- app/views/campaign/child/_consent-banner-3-in-1.html
- app/views/campaign/child/_consent-banner.html
- app/views/campaign/child/_consent-triage.html
- app/views/campaign/child/_details.html
- app/views/campaign/child/_outcome-banner.html
Before this change, the following 3 fields sat on the `child` record, not nested under `child.consent`:
* `child.consentedDate`
* `child.consentedMethod`
* `child.parentOrGuardian`
In order to support multiple consents further down the line, these should sit together with the other consent fields.
> Tidy up how consent is modelled in the prototype generated data

- package-lock.json
- package.json
This bump seems to break CSS generation on Heroku.
> Revert rollup-plugin-scss to v3

- app/views/_components/heading/macro.njk
- app/views/_components/heading/template.njk
- app/views/campaign/child/_action-vaccinate-options.html
- app/views/consent/consent.html
- app/views/consent/gillick.html
- app/views/consent/health-questions.html
- app/views/consent/index.html
- app/views/consent/pre-gillick.html
- app/views/consent/why-not-consenting.html
- app/views/layouts/default.html
- app/views/vaccination/not-given.html
- app/views/vaccination/other-site.html
- app/views/vaccination/which-batch.html
During the model office, it was noted that it’s sometimes hard to keep track of which child an action is being taken against.
We can address this by always showing the child’s name above the page title in a caption:
> Show child’s name as heading cation on relevant flows

- app/assets/stylesheets/application.scss
- app/views/campaign/_children-banner.html
- app/views/campaign/child/_vaccination-recorded.html
- app/views/campaign/index.html
- app/views/campaign/new/check.html
- app/views/consent/confirm.html
- app/views/manage-users.html
- app/views/vaccination/_multiple-vaccine-details.html
- app/views/vaccination/_single-vaccine-details.html
- app/views/vaccination/confirmation.html
We can set the default font family for imported GOV.UK Design System components by setting `$govuk-font-family`, as opposed to using a utility class.
> Set default font family for GOV.UK components

- app/generators/consent.js
- app/routes/consent.js
- app/views/campaign/child/_action-get-consent.html
- app/views/campaign/child/_consent-log.html
- app/views/campaign/child/_consent-triage.html
- app/views/consent/confirm.html
This PR splits out the ability to capture information relating to obtaining consent from those relating to triaging medical history.
Like triage notes, a table is shown showing any consent related notes that have been added:
* During triage:
* During record:
Like the flow for adding triage notes, notes about consent can be added on the check answers page when completing the get consent flow. 
This still needs more refinement, but this PR adds the basic functionality and hopefully corrects some of the logic around collecting notes while attempting to obtain consent.
> Add consent log

- app/views/campaign/child.html
Also use constant enums in logic checks on child details page.
> Do not show vaccination actions if triage outcome was ‘Do not vaccinate’

- app/enums.js
- app/generators/campaign-in-progress.js
- app/generators/campaign.js
- app/generators/child.js
- app/generators/consent-responses.js
- app/generators/consent.js
- app/generators/derived-consent.js
- app/generators/health-answers.js
- app/generators/health-questions.js
- app/generators/refusal.js
- app/generators/triage-needed.js
- app/routes/consent.js
- app/views/campaign/child-triage.html
- app/views/campaign/child.html
- app/views/campaign/child/_consent-triage.html
- app/views/campaign/child/_details.html
- app/views/campaign/child/_health-questions.html
- app/views/consent/health-questions.html
Update data model to allow a child to have multiple constant responses (`child.consentResponses`), each containing consent data and health answers. The `child.consent` value now returns values derived from all responses.
PR also splits apart health questions for each vaccine from answers provided in a consent response, and displays multiple consent responses in the UI:
Later PRs will allow users to select the accepted consent response and add any notes about attempting to obtain consent.
> Multiple consents

- app/generators/derived-consent.js
- app/views/campaign/_children-tab.html
- app/views/campaign/_children-triage-tab.html
- app/views/campaign/children-triage.html
Added refusal reasons (plural if multiple consent responses) to a new column under the ‘Get consent’ column:
Also reduced the font size of triage reasons, date of birth and name known by, as table getting a bit cramped. Which suggests may need to review the presentation of this info later.
> Show refusal reasons in triage table

- app/views/index.html
Looks like the redirect was changed a few commits ago.
> Fix link to record vaccinations view

- app/enums.js
- app/generators/campaign.js
- app/generators/patient.js
- app/generators/response.js
- app/routes.js
- app/routes/_filters.js
- app/utils/consent-outcome.js
- app/utils/triage-outcome.js
- app/views/campaign/patient.html
Instead of updating triage and consent outcomes when generating session data, instead derive these values on each page view. This means that each time session data is updated, pages will reflect the current derived outcomes, records will appear in the correct views and with the correct outcome banner.
Also:
* Show a maximum of 3 consent responses instead of 4
* Fix derived consent generator so that responses are individual (thus creating records with conflicting consent)
* Document a few more data models using JSDoc
> Dynamic derive triage and consent outcomes

- app/generators/patient.js
- app/generators/vaccination.js
- app/globals.js
- app/routes/campaign.js
- app/utils/consent-outcome.js
- app/utils/triage-outcome.js
- app/views/_macros/sessions.njk
* Patients in triage no longer change on page refresh
* Several triage notes without content no longer get applied to patient records
* Show name of the nurse in banner (taking the user name from the more recent triage note)
* Ensure triage action is shown on patient record, instead of remaining as ‘Triage needed’
> Fix triage journey

- app/assets/stylesheets/application.scss
- app/globals.js
- app/routes/_filters.js
- app/views/campaign/_tab.html
- app/views/campaign/patient.html
- app/views/campaign/patient/_outcome.html
* Show relationship names in consent/refusal summary
* Remove status tag from most session tables
* Show confirmed refusal status in consent refused table
* Only show vaccination action panel when a campaign is in progress
* Show correct content in outcome summary panel
> Consent design review (part 2)

- app/assets/stylesheets/application.scss
- app/routes.js
- app/routes/account.js
- app/views/_layouts/default.html
- app/views/account/sign-in.html
- app/views/dashboard.html
- app/views/index.html
* Add sign out link (and non-working account link) to header navigation
* Add links to school sessions and manage vaccines views to header navigation
* Set `req.session.data.token` value to `'true'` when signing in
* Delete `req.session.data.token` when signing out
* Only show signed in navigation when `req.session.data.token` is true
* Use alphabetical order for loading routes (hope this doesn’t bite me…)
> Add signed in header navigation and sign out route

- app/routes/consent.js
- app/views/consent/index.html
Instead of allowing user to enter details manually, let them choose from a pre-defined list of contacts (that in theory would come from CHIS records and perhaps other sources). This replaces the journey where details would need to be entered manually.
> Show pre-defined list of parental contacts for get consent response journey

- README.md
- app/views/dashboard.html
- app/views/emails/invite-new-user.html
- app/views/index.html
- package.json
During research with SAIS teams, we received feedback on the service name, chiefly that a shorter name for the service would be useful when referencing it within teams, as is the case with existing systems.
However, this need should be weighed up against guidance that service names should use verbs, not nouns.
However, whatever we call it, a shorthand will end up being used by SAIS teams, so it makes sense for us to think of a name ahead of time that can be easily abbreviated, and hint towards that appreciation being approved.
Changing the name from ‘Manage vaccinations for school-aged children’ to ‘Manage vaccinations in schools’, not only do we have a shorter ‘official’ name, but this can be abbreviated to ‘MAVIS’.[^1]
This PR renames the service to ‘Manage vaccinations in schools’, …
> Update service name

- app/fakers/batch.js
- app/filters.js
- app/utils/campaign.js
- app/views/patient/_outcome.html
- app/views/vaccination/_single-vaccine-summary.html
- app/views/vaccines/index.html
1. For vaccines, show supplier and GTIN code and for a batch show when it was entered into MAVIS:
We don’t have any flows for adding vaccines yet, but it’s likely we wouldn’t ask users to enter any besides a GTIN code, and then potentially pull the necessary data from an upstream data source? TBD.
2. When vaccinating, show the dosage in millilitres:
> Add additional metadata for vaccines, batches and doses

- app/fakers/response.js
- app/fakers/user.js
- app/views/_macros/events-list.njk
- app/views/patient/_outcome.html
- app/views/users/index.html
- app/views/users/new.html
- app/views/users/user.html
- app/views/vaccination/_multiple-vaccine-summary.html
- app/views/vaccination/_single-vaccine-summary.html
Show registration number, with registration body initials in brackets
We don’t have a signup flow yet, but we’d ask for professional body and registration number there, so for inviting a user, keep this page to just name and email address:
A user could edit these values, but we don’t have that flow design yet. Should an admin be able to edit these details? TBD, but for now, I’ve added fields for professional body and registration number to the edit user page:
Throughout the interface, wherever we show a user, we show their registration number after their name, for example in triage notes:
We also show registration number in a vaccination outcome. Here, also showing the hardcoded protocol vaccinations are undertaken under:
> Add ability to add, edit and show user registration numbers

- app/assets/stylesheets/application.scss
- app/views/_layouts/default.html
- app/views/pilot/screener/index.html
> Add phase banner, additional checkbox to screener

- app/fakers/response.js
- app/filters.js
- app/views/response/_patient-summary.html
- app/views/response/archive.html
- app/views/response/index.html
- app/views/response/match.html
- app/views/schools/school.html
- app/views/sessions/_tab.html
- app/views/sessions/new/cohort.html
- app/views/sessions/unmatched-responses.html
- app/views/users/index.html
- Archive unmatched consent responses rather than delete them
- Show archived responses on unmatched responses page
- Show visually hidden text (‘Inconsistent: ’) for highlighted differences on linking page
- Remove links to response on matching view, only provide link to ‘Select’
- Revert back to showing patients full name (‘firstName lastName’) instead of ‘lastName, firstName’
> Unmatched responses

- app/routes/new-session.js
- app/views/sessions/edit.html
- app/views/sessions/new/confirm.html
- app/views/sessions/new/schedule.html
- app/views/sessions/session.html
Update schedule form so that:
- Change to only being able to enter a date for when consent requests should be sent (can be today’s date)
- Change default for sending reminders from 7 days to 2 days
- Leave closing consent requests as previous
Unchanged if date for sending consent requests is in the future:
If the entered date is today, add additional context above the ‘Confirm’ button:
(Idea is that, we’d have a task that sends consent requests on the hour, so if you entered today’s date, and the time now is 2:29pm, emails would be sent at 3pm)
Add link to edit screen from session landing page:
Add edit screen, so that some values can be changed:
- Type of session
- Date and time of session
- Date to send consent requests (if not already sent)
- Date to send reminders (if not already …
> Update session scheduling and allow editing a session
