nhsuk/manage-childrens-vaccinations-prototype

app/generators/health-questions.js
app/routes.js
app/routes/campaign.js
app/routes/online-offline.js
app/views/back-online.html
app/views/consent/gillick.html
app/views/give-offline-code.html
app/views/layouts/default.html
app/views/offline-code.html
app/views/offline-password.html
app/views/set-offline-code.html
app/wizards/consent.js
app/wizards/vaccination.js

https://user-images.githubusercontent.com/319055/236440726-2fe87456-a89c-41c1-82ab-9e259a1d7b74.mov

Add offline code designs

---

app/generators/campaign.js

We need to be able to see the designs for the other types of vaccination.

Generate fake data for flu and 3-in-1 and MenACWY, alongside HPV

---

app/assets/stylesheets/components/_consent-banner.scss
app/assets/stylesheets/components/_outcome-tag.scss
app/enums.js
app/generators/campaign-in-progress.js
app/generators/campaign.js
app/generators/child.js
app/generators/health-questions.js
app/generators/parent.js
app/generators/triage-needed.js
app/globals.js
app/routes/_filter-children.js
app/routes/campaign.js
app/routes/vaccination.js
app/views/_components/actionNeededTag/macro.njk
app/views/_components/actionNeededTag/template.njk
app/views/_components/actionTakenTag/macro.njk
app/views/_components/actionTakenTag/template.njk
app/views/campaign/_children-tab.html
app/views/campaign/_children-triage-tab.html
app/views/campaign/_filters.html
app/views/campaign/child.html
app/views/campaign/child/_consent-banner.html
app/views/campaign/children-triage.html
app/views/campaign/children.html
app/views/layouts/default.html
package-lock.json
package.json

https://github.com/nhsuk/record-childrens-vaccinations-prototype/assets/319055/c43b8d99-8c01-4563-a0a5-8554e0a121b1

Add tabs to record vaccs and triage

---

app/routes/campaign.js
app/views/campaign/_children-banner.html
app/views/campaign/child/_consent-triage.html

https://github.com/nhsuk/record-childrens-vaccinations-prototype/assets/23801/af715d60-a6e6-4885-a9a1-2915977abb23

Triage: allow notes to be saved when there's no consent

---

app/enums.js
app/generators/parent.js
app/generators/triage-needed.js

* Change ‘Notes need triage’ to ‘Health questions need triage’
* Remove triaging around for checking parental responsibility (this is now asked during consent journey)

Update triage reasons

---

app/assets/stylesheets/components/_consent-banner.scss
app/views/_components/consentBanner/macro.njk
app/views/_components/consentBanner/template.njk
app/views/campaign/child/_consent-banner-3-in-1.html
app/views/campaign/child/_consent-banner.html
app/views/campaign/child/_outcome-banner.html
app/views/campaign/child/_triage-banner.html
app/views/layouts/default.html

* Makes content banner a component
* Updates CSS to more closely match `nhsuk-card` and depend less on inline utility classes

Refactor consent banner component

---

app/views/campaign/child/_action-get-consent.html

Change consent question option to ‘No, I am not vaccinating’

---

app/views/consent/consent.html

SAIS teams administer a single dose now.

Remove references to 2 doses of HPV in Gillick flow

---

app/assets/stylesheets/application.scss
app/enums.js
app/generators/patient.js
app/generators/response.js
app/globals.js
app/routes/consent.js
app/utils/consent-outcome.js
app/views/_layouts/default.html
app/views/_macros/events-list.njk
app/views/_macros/sessions.njk
app/views/campaign/index.html
app/views/campaign/patient.html
app/views/campaign/patient/_consent.html
app/views/campaign/patient/_response-summary.html
app/views/campaign/record.html
app/views/campaign/responses.html
app/views/campaign/triage.html
app/views/consent/confirm.html
app/views/consent/consent.html
app/wizards/consent.js
package-lock.json
package.json

Remove consent log and show events against each respondent instead

---

app/globals.js

THis change fixes a crash after a vaccination even is recorded. It *might* have been introduced by https://github.com/nhsuk/record-childrens-vaccinations-prototype/commit/2685929d13ceb00cca750f538cca3aaa9b2315cb

Fix recording of vaccinations

---

app/enums.js
app/globals.js
app/routes.js
app/routes/_filters.js
app/utils/consent-outcome.js
app/utils/patient-outcome.js
app/views/campaign/patient/_consent.html

* Update content based on team feedback
* Ensure refused consent records get moved to Refusal in consent table, Could not vaccinate in record table
* Fix refusal reasons not being updated after confirming refusal
* Fix patients with health questions not appearing in triage needed table
* Update overall patient outcome based on consent and triage outcomes

Consent tweaks and fixes

---

app/globals.js
app/routes/_filters.js
app/routes/campaign.js
app/views/campaign/index.html
app/views/campaign/patient.html
app/views/campaign/patient/_action-triage.html

The lower-hanging tweaks:
* Remove ‘or’ divider on triage options
* Prepend user name with ‘Nurse’ in triage summary
* Add summary counts to session page:

Consent design review (part 1)

---

app/routes/vaccination.js
app/views/campaign/patient.html
app/views/campaign/patient/_action-vaccinate.html
app/views/campaign/patient/_outcome.html
app/views/vaccination/_single-vaccine-details.html
app/wizards/vaccination.js

Reimplements #127 and record a `PART_VACCINATION` vaccination outcome.

Reimplement ability to record half a flu dose

---

app/routes/consent.js

Previously showed child as consenting party, regardless of an example parent being selected.

Show correct consenting party in consent response

---

app/assets/javascripts/pilot.js
app/assets/stylesheets/pilot.scss
app/views/_layouts/pilot.html
app/views/pilot/confirmation.html
app/views/pilot/screener.html
rollup.config.js

Screener for pilot

---

app/assets/javascripts/application.js
app/assets/stylesheets/_action-table.scss
app/assets/stylesheets/_button.scss
app/assets/stylesheets/_list.scss
app/assets/stylesheets/application.scss
app/fakers/year-group.js
app/globals.js
app/views/_macros/sessions.njk
app/views/sessions/_filters.html
app/views/sessions/_tab.html
package-lock.json
package.json

Use `action-table` web components to implement sorting and filtering on session and patient tables. Potentially an option for production, too.

Add and update filtering and sorting of tables

---

app/assets/downloads/expressions-of-interest.csv
app/assets/stylesheets/application.scss
app/views/dashboard.html
app/views/pilot/close-screener.html
app/views/pilot/cohort-upload-errors.html
app/views/pilot/cohort-upload-success.html
app/views/pilot/cohort.html
app/views/pilot/index.html
app/views/pilot/participants.html
app/views/pilot/screener/closed.html

Pilot data refinements [WIP]

---

app/routes/new-session.js
app/views/response/match.html
app/views/schools/school.html
app/views/sessions/_tab.html
app/views/sessions/new/cohort.html
app/views/sessions/unmatched-responses.html
app/views/users/index.html

When listing patients in table views, use `{{ patient.lastName }}, {{ patient.firstName}}` format, and sort by `patient.lastName`.

Show patient’s last name before first name, sort by last name

---

app/assets/stylesheets/_action-table.scss
app/assets/stylesheets/_tabs.scss
app/assets/stylesheets/application.scss
app/routes/_filters.js
app/views/sessions/_filters.html
app/views/sessions/_tab.html
app/views/sessions/record.html
app/views/sessions/responses.html
app/views/sessions/triage.html

- Shorter tab titles
- Add caption to patient tables
- Hide filters on mobile and when JavaScript has not loaded `action-table-filters` component
- Use fieldset to contain filters

Improve mobile layout and patient table accessibility

---

app/views/sessions/new/no-cohort.html

Shown after selecting a school which has no children left that need adding to a session.

Add page if no children remaining in cohort
